package org.golovko.telegramshop.botapi;

public enum BotState {
    START,
    QUESTIONS,
    SHOW_MAIN_MENU,
    SHOW_MY_ORDERS,
    SHOW_CATALOG,
    SHOW_SHOPPING_CART,
    SHOW_CONTACTS,
    FILLING_ORDER_INFO,
    ENTER_FULL_NAME,
    ENTER_PHONE,
    ENTER_CITY,
    ENTER_ADDRESS,
    CHOOSE_PAYMENT_TYPE,
    CONFIRM_ORDER
}
